### ISSUE TITLE
Guzzle version

### ISSUE THREAD

**Issue by Borales** [2amigos/yii2-google-places-library#2]
Hi!
Is there a reason for limiting Guzzle version up to "4.*"?

```
"guzzlehttp/guzzle": "4.*"
```

The current version of Guzzle is 5.2

Thanks.

**Comment by tonydspaniard** [comment]
Normally, when I created extensions in the past, they tend to change their API without considering B/C. This way I ensure that the extension works at all times.

I think is httpGuzzle now right?I will test it, or a nice PR would be more than welcome.

**Comment by Borales** [comment]
@tonydspaniard I just wasn't sure about the purpose of doing that.
I'll make a PR

**Comment by tonydspaniard** [comment]
@Borales Thanks!

**Comment by Borales** [comment]
@tonydspaniard I've made a PR. Seems everything should work normal.

Btw, for some reason even after a "clean" install of composer packages - Client.php wasn't unable to find a couple of classes.
![2015-02-12 18 11 55](https://cloud.githubusercontent.com/assets/1118933/6172891/07bd89c0-b2e4-11e4-9852-5522fe2040c3.png)
![2015-02-12 18 12 03](https://cloud.githubusercontent.com/assets/1118933/6172892/07bf5a34-b2e4-11e4-97cd-d5abf2858f2e.png)

**Comment by tonydspaniard** [comment]
The reason is that you have to use the GuzzleHttp namespace, those classes do not exist anymore

**Comment by Borales** [comment]
@tonydspaniard yes, I know that :) I meant those namespaces are present in this working plugin

**Comment by tonydspaniard** [comment]
@Borales Thanks.. Will try to update when refactoring the extension to match new http://yiiwheels.com standards.

**Comment by Borales** [comment]
@tonydspaniard I think I can close this issue now, thanks.

**Comment by tonydspaniard** [comment]
@Borales my pleasure. I still need to revisit the extension. Quite busy lately. Hope I can do it this week.
