### ISSUE TITLE
In have this error

### ISSUE THREAD

**Issue by McNamara10** [2amigos/yii2-google-places-library#7]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii2-google-places-library * -> satisfiable by 2amigos/yii2-google-places-library[0.1.0].
    - Conclusion: remove guzzlehttp/guzzle 6.2.2
    - Conclusion: don't install guzzlehttp/guzzle 6.2.2
    - 2amigos/yii2-google-places-library 0.1.0 requires guzzlehttp/guzzle 4.* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4].
    - Can only install one of: guzzlehttp/guzzle[4.0.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.0.1, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.0.2, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.1, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.2, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.3, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.4, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.5, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.6, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.7, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.8, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.0, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.1, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.2, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.3, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.4, 6.2.2].
    - Installation request for guzzlehttp/guzzle (locked at 6.2.2) -> satisfiable by guzzlehttp/guzzle[6.2.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by tonydspaniard** [comment]
Thanks. I'll investigate the issue asap.

**Comment by robwent** [comment]
Guzzle 4.* is also incompatible with php 7.1. I get

    Cannot use lexical variable $eventName as a parameter name
     in ...\vendor\guzzlehttp\guzzle\src\Event\Emitter.php at line 49

I'm just trying to update, I will report back if I can get it going.

**Comment by tonydspaniard** [comment]
@robwent @McNamara10 should be fixed on 1.0.*
