### ISSUE TITLE
Key or format can not be empty

### ISSUE THREAD

**Issue by lnghost** [2amigos/yii2-google-places-library#8]
https://github.com/2amigos/yii2-google-places-library/blob/master/src/AbstractComponent.php#L57

This code calls not to class property, and i have an exception, because $key and $format variables don't isset.

**Comment by tonydspaniard** [comment]
Thank you very much... what a silly mistake 🥇

**Comment by lnghost** [comment]
Please update 1.0.1 version or create new one.

**Comment by tonydspaniard** [comment]
@lnghost you can update the library now. Apologies... Fixed on 1.0.2
